spring:
  datasource:
    url: jdbc:postgresql://localhost/chronos_import
    username: chronos
    password: chronos
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
