spring:
  profiles:
    default: h2

microsoft:
  graph:
    auth:
      clientId: secret
      clientSecret: secret
      authorityHost: secret
      tenantId: secret
      scopes: User.Read

hibernate:
  globally_quoted_identifiers: true


logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:
        type:
          descriptor:
            sql:
              BasicBinder=TRACE:
